# Generated by Django 4.2.13 on 2026-05-18 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Movie duration in minutes')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Rating out of 10', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('now_showing', 'Now Showing'), ('ended', 'Ended')], db_index=True, default='upcoming', max_length=20)),
                ('poster_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated cast names')),
                ('certificate', models.CharField(blank=True, help_text='Age certificate: U, UA, A, S', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, db_table='movie_genres', related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(blank=True, db_table='movie_languages', related_name='movies', to='movies.language')),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_active'], name='idx_language_active'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='idx_language_code'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_active'], name='idx_genre_active'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='idx_genre_slug'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='idx_movie_rating'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='idx_movie_release_date'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status'], name='idx_movie_status'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active'], name='idx_movie_active'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_featured'], name='idx_movie_featured'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active', '-rating'], name='idx_movie_active_rating'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active', '-release_date'], name='idx_movie_active_release'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='idx_movie_title'),
        ),
    ]
